### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [zeek/tree-sitter-zeek-src#2]
Using this page https://meimporta.eu/tree-sitter/json2ebnf.html we can get a navigable railroad diagram for tree-sitter grammars like this project.

See also https://github.com/tree-sitter/tree-sitter/issues/2268 .

Cheers !

**Comment by bbannier** [comment]
I am unsure there is anything to do here since the actual discussion is happening in https://github.com/tree-sitter/tree-sitter/issues/2268. Could you close this @ckreibich?

**Comment by ckreibich** [comment]
Yeah, closing. I also tweaked the permissions on this repo so you should be able to do this too going forward.
